### PR TITLE
WIP-Changed css to how events display

### PR DESCRIPTION
**Pull request by emwiedoff**

### CODE REVIEW

**Comment by vangheem** [comment]
Is this still relevant?

**Comment by emwiedoff** [comment]
Yes, I believe so.

**Comment by vangheem** [comment]
Safe to merge? Should it still be WIP?

**Comment by emwiedoff** [comment]
You can merge it.

**Comment by vangheem** [comment]
Cool, moved to https://github.com/castlecms/castle.theme/pull/7

Closing. Looks good.

**Pull request closed without merging**
